name: APKLEAKS Auto-Workflow

on:
  workflow_dispatch:
    inputs:
      apk_path:
        description: 'Pfad zu der einzelnen APK-Datei (z.B. "apk/app.apk")'
        required: true
        default: 'apk/FSEX MAX_1.0.1_apks.apk'

jobs:
  scan-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq zip

      - name: Install APKLeaks latest from GitHub
        run: |
          pip install --upgrade git+https://github.com/dwisiswant0/apkleaks.git@main

      - name: Validate APK Path
        run: |
          FILES=(${{ inputs.apk_path }})
          if [ ${#FILES[@]} -ne 1 ]; then
            echo "Error: Exactly one APK file must be specified. Found ${#FILES[@]}."
            exit 1
          fi
          if [ ! -f "${FILES[0]}" ]; then
            echo "Error: APK file not found: ${FILES[0]}"
            exit 1
          fi
          echo "Validated APK file: ${FILES[0]}"

      - name: Scan APK
        id: scan
        run: |
          APK_FILE="${{ inputs.apk_path }}"
          APK_NAME=$(basename "$APK_FILE" .apk)
          DATE=$(date +'%Y-%m-%d_%H-%M')
          VERSION="run-${GITHUB_RUN_NUMBER}"
          OUTPUT_DIR="apkleaks_output/${APK_NAME}_${DATE}_${VERSION}"
          mkdir -p "$OUTPUT_DIR"

          echo "Scanning $APK_FILE ..."
          apkleaks -f "$APK_FILE" -o "$OUTPUT_DIR/apkleaks.json" || true

          # HTML-Report mit jq
          HTML_FILE="${OUTPUT_DIR}/${APK_NAME}_${DATE}_${VERSION}_report.html"
          if [ -f "$OUTPUT_DIR/apkleaks.json" ]; then
            jq -r \
              '"<html><head><title>APKLeaks Report</title></head><body><h1>APKLeaks Report</h1><pre>" + tostring + "</pre></body></html>"' \
              "$OUTPUT_DIR/apkleaks.json" > "$HTML_FILE"
          fi

          # ZIP alle Outputs
          ZIP_FILE="apkleaks_output/${APK_NAME}_${DATE}_${VERSION}_apkleaks.zip"
          cd "$OUTPUT_DIR"
          zip -r "../../${ZIP_FILE}" .
          cd ../..

          # Outputs für den Release
          RELEASE_NAME="${APK_NAME}_${DATE}_${VERSION}_APKLeaks"
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
          echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT
          echo "html_file=$HTML_FILE" >> $GITHUB_OUTPUT
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT

      - name: Upload Workflow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apkleaks-results-${{ steps.scan.outputs.apk_name }}
          path: |
            ${{ steps.scan.outputs.zip_file }}
            ${{ steps.scan.outputs.html_file }}

      - name: Create GitHub Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: "apkleaks-${GITHUB_RUN_NUMBER}"
          name: ${{ steps.scan.outputs.release_name }}
          body: |
            **APKLeaks Scan Report**
            - APK: `${{ steps.scan.outputs.apk_name }}`
            - Date: $(date +'%Y-%m-%d %H:%M')
            - Version: run-${GITHUB_RUN_NUMBER}
            - Triggered by: ${{ github.actor }}

            The release contains the full scan results:
            - ZIP archive
            - HTML report (clickable)
          artifacts: |
            ${{ steps.scan.outputs.zip_file }}
            ${{ steps.scan.outputs.html_file }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: falsename: APKLEAKS Auto-Workflow

on:
  workflow_dispatch:
    inputs:
      apk_path:
        description: 'Pfad zu der einzelnen APK-Datei (z.B. "apk/app.apk")'
        required: true
        default: 'apk/ZEUS_9.40.apk'

jobs:
  scan-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq zip

      - name: Install APKLeaks latest from GitHub
        run: |
          pip install --upgrade git+https://github.com/dwisiswant0/apkleaks.git@main

      - name: Validate APK Path
        run: |
          FILES=(${{ inputs.apk_path }})
          if [ ${#FILES[@]} -ne 1 ]; then
            echo "Error: Exactly one APK file must be specified. Found ${#FILES[@]}."
            exit 1
          fi
          if [ ! -f "${FILES[0]}" ]; then
            echo "Error: APK file not found: ${FILES[0]}"
            exit 1
          fi
          echo "Validated APK file: ${FILES[0]}"

      - name: Scan APK
        id: scan
        run: |
          APK_FILE="${{ inputs.apk_path }}"
          APK_NAME=$(basename "$APK_FILE" .apk)
          DATE=$(date +'%Y-%m-%d_%H-%M')
          VERSION="run-${GITHUB_RUN_NUMBER}"
          OUTPUT_DIR="apkleaks_output/${APK_NAME}_${DATE}_${VERSION}"
          mkdir -p "$OUTPUT_DIR"

          echo "Scanning $APK_FILE ..."
          apkleaks -f "$APK_FILE" -o "$OUTPUT_DIR/apkleaks.json" || true

          # HTML-Report mit jq
          HTML_FILE="${OUTPUT_DIR}/${APK_NAME}_${DATE}_${VERSION}_report.html"
          if [ -f "$OUTPUT_DIR/apkleaks.json" ]; then
            jq -r \
              '"<html><head><title>APKLeaks Report</title></head><body><h1>APKLeaks Report</h1><pre>" + tostring + "</pre></body></html>"' \
              "$OUTPUT_DIR/apkleaks.json" > "$HTML_FILE"
          fi

          # ZIP alle Outputs
          ZIP_FILE="apkleaks_output/${APK_NAME}_${DATE}_${VERSION}_apkleaks.zip"
          cd "$OUTPUT_DIR"
          zip -r "../../${ZIP_FILE}" .
          cd ../..

          # Outputs für den Release
          RELEASE_NAME="${APK_NAME}_${DATE}_${VERSION}_APKLeaks"
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
          echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT
          echo "html_file=$HTML_FILE" >> $GITHUB_OUTPUT
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT

      - name: Upload Workflow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apkleaks-results-${{ steps.scan.outputs.apk_name }}
          path: |
            ${{ steps.scan.outputs.zip_file }}
            ${{ steps.scan.outputs.html_file }}

      - name: Create GitHub Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: "apkleaks-${GITHUB_RUN_NUMBER}"
          name: ${{ steps.scan.outputs.release_name }}
          body: |
            **APKLeaks Scan Report**
            - APK: `${{ steps.scan.outputs.apk_name }}`
            - Date: $(date +'%Y-%m-%d %H:%M')
            - Version: run-${GITHUB_RUN_NUMBER}
            - Triggered by: ${{ github.actor }}

            The release contains the full scan results:
            - ZIP archive
            - HTML report (clickable)
          artifacts: |
            ${{ steps.scan.outputs.zip_file }}
            ${{ steps.scan.outputs.html_file }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
